# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam', '0002_trip_month_day_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='month_day_year',
        ),
        migrations.AddField(
            model_name='trip',
            name='end_month_day_year',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_month_day_year',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
