# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam', '0003_auto_20180417_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
