# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam', '0005_auto_20180417_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_month_day_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_month_day_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
